#!/bin/bash
set -euo pipefail

# wrapper script
temp_dir=$(mktemp --directory)
temp_file="${temp_dir}/a.torrent"

if test "$1" == "-" ; then
    cat </dev/stdin >"${temp_file}"
else
    cp "$1" "${temp_file}"
fi

sudo docker run \
    --rm \
    --volume "${temp_dir}:/input" \
    btshowmetainfo/btshowmetainfo

rm -rf "${temp_dir}"
