#!/bin/bash
set -euo pipefail

echo "building..."
TAG=btshowmetainfo/btshowmetainfo
docker build -t $TAG .
echo "built. testing..."

function test {
    mkdir -p ./input
    cp ./input_/$f ./input/a.torrent
    docker run \
        --rm \
        --volume "$(pwd)/input:/input" \
        $TAG | grep "$h"
}

f='ubuntu-18.04.4-desktop-amd64.iso.torrent'
h='286d2e5b4f8369855328336ac1263ae02a7a60d5'
test

f='ubuntu-20.04.2-live-server-amd64.iso.torrent'
h='126f82fb33119d2acf93a16cfba6eb1c5787a59f'
test

echo "repeat test with driver script 1"
f='./input_/ubuntu-20.04.2-live-server-amd64.iso.torrent'
./btshowmetainfo - < $f | grep "$h"

echo "repeat test with driver script 2"
f='./input_/ubuntu-20.04.2-live-server-amd64.iso.torrent'
./btshowmetainfo $f | grep "$h"

echo "BUILD AND TEST SUCCESSFUL."